Domain\Item\Item:
  type: entity
  table: items
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
      options:
        unsigned: true
  fields:
    name:
      type: string
      length: 50
